version: '3'
services:
  bot:
    build: ./
    restart: always
    environment: #these are regular environment variables, please tell me if you add any more
      TOKEN: #delete this comment and paste the bot token here
      PREFIX: "!"
  mysql:
    image: "mysql:latest"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: railerbot
      MYSQL_DATABASE: railer-db
    volumes:
      - lchs-bot-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    links:
      - bot
      - phpmyadmin
  phpmyadmin:
    image: "phpmyadmin/phpmyadmin:latest"
    restart: always
    environment:
      PMA_HOST: mysql
    ports:
     - "6980:80"
volumes:
  lchs-bot-data:
